// SPDX-License-Identifier: GPL-3.0-or-later
package com.calebc42.composer.model

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Contract tests over the REAL committed manifest — the vendored
 * glasspane-pack.json (generated by glasspane-pack.el from the live
 * jetpacs-source-catalog / jetpacs-action-catalog, byte-stable). If this
 * file stops parsing, the composer and the reference pack have drifted.
 */
class PackManifestTest {

    private fun vendoredText(): String =
        PackManifestTest::class.java.getResourceAsStream("/glasspane-pack.json")!!
            .bufferedReader(Charsets.UTF_8).readText()

    @Test
    fun parsesTheCommittedGlasspaneManifest() {
        val pack = PackManifest.parse(vendoredText())
        assertEquals("glasspane", pack.pack_id)
        assertEquals("1.0.0", pack.pack_version)
        assertEquals("glasspane", pack.feature)
        assertEquals("1.5.0", pack.min_jetpacs_api)
        assertEquals(listOf("org", "org-ql", "vulpea", "cl-lib"),
                     pack.depends.map { it.name })
        assertEquals(listOf("list", "board", "calendar"), pack.layouts)
        assertEquals(listOf("glasspane.notes", "glasspane.org"),
                     pack.sources.map { it.name })

        val notes = pack.source("glasspane.notes")!!
        assertEquals(listOf("id", "relation"), notes.params.map { it.name })
        assertTrue(notes.params[0].required)
        assertEquals("enum", notes.params[1].type)
        assertEquals(listOf("backlinks", "outgoing"), notes.params[1].values)
        assertEquals("string-list",
                     notes.fields.find { it.name == "tags" }!!.type)

        assertEquals(11, pack.actions.size)
        val schedule = pack.action("heading.schedule")!!
        assertNotNull(schedule.doc)
        assertEquals(listOf("ref", "when", "value", "clear"),
                     schedule.args.map { it.name })
        assertEquals("bool", schedule.args.last().type)
    }

    @Test
    fun manifestRoundTripsThroughItsJsonForm() {
        val once = PackManifest.parse(vendoredText())
        assertEquals(once, PackManifest.parse(PackManifest.encode(once)))
    }

    @Test
    fun rejectsStructurallyBrokenManifests() {
        // Field type outside the closed source vocabulary.
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse(
                """{"pack_id":"x","pack_version":"1","feature":"x",
                    "sources":[{"name":"s","fields":[{"name":"f","type":"florb"}]}]}""")
        }
        // Enum without values.
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse(
                """{"pack_id":"x","pack_version":"1","feature":"x",
                    "sources":[{"name":"s","params":[{"name":"p","type":"enum"}]}]}""")
        }
        // Action arg outside the defaction arg vocabulary ("boolean" is
        // source-side; actions say "bool").
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse(
                """{"pack_id":"x","pack_version":"1","feature":"x",
                    "actions":[{"action":"a","args":[{"name":"z","type":"boolean"}]}]}""")
        }
        // Bad pack id.
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse("""{"pack_id":"Bad Id","pack_version":"1","feature":"x"}""")
        }
    }

    @Test
    fun rejectsFeaturelessOrUnsafeFeatureManifests() {
        // No feature: unusable — the runtime requires it to load, so every
        // view would fail closed on device. Reject at parse instead.
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse("""{"pack_id":"x","pack_version":"1"}""")
        }
        // A feature that isn't a bare symbol name is an injection surface in
        // the trusted registration the bundle emits.
        assertFailsWith<IllegalArgumentException> {
            PackManifest.parse(
                """{"pack_id":"x","pack_version":"1","feature":"x) (evil"}""")
        }
    }

    @Test
    fun unknownJsonKeysAreForwardCompatible() {
        val pack = PackManifest.parse(
            """{"pack_id":"x","pack_version":"1","feature":"x","future_key":{"nested":true}}""")
        assertEquals("x", pack.pack_id)
    }

    // ─── The registry (installed-manifest store) ─────────────────────────

    private fun tempDir(): File =
        File.createTempFile("packs", null).also { it.delete(); it.mkdirs(); it.deleteOnExit() }

    private fun minimal(id: String, version: String = "1.0.0") =
        """{"pack_id":"$id","pack_version":"$version","feature":"$id"}"""

    @Test
    fun loadsManifestsFromTheConfiguredDirectory() {
        val dir = tempDir()
        File(dir, "alpha-pack.json").writeText(minimal("alpha"))
        File(dir, "beta-pack.json").writeText(minimal("beta"))
        File(dir, "notes.txt").writeText("not a manifest")
        val registry = PackRegistry.load(dir)
        assertNotNull(registry.byId("alpha"))
        assertNotNull(registry.byId("beta"))
        assertTrue(registry.problems.isEmpty())
        // The vendored reference joins alongside user manifests.
        assertNotNull(registry.byId("glasspane"))
    }

    @Test
    fun duplicatePackIdsFailClosed() {
        val dir = tempDir()
        File(dir, "one-pack.json").writeText(minimal("alpha", "1.0.0"))
        File(dir, "two-pack.json").writeText(minimal("alpha", "2.0.0"))
        val registry = PackRegistry.load(dir)
        // Neither claimant is served — the composer never silently picks one.
        assertNull(registry.byId("alpha"))
        assertTrue(registry.problems.any { "alpha" in it })
    }

    @Test
    fun unparsableManifestBecomesAProblemNotAnException() {
        val dir = tempDir()
        File(dir, "broken-pack.json").writeText("{not json")
        File(dir, "good-pack.json").writeText(minimal("good"))
        val registry = PackRegistry.load(dir)
        assertNotNull(registry.byId("good"))
        assertTrue(registry.problems.any { "broken-pack.json" in it })
    }

    @Test
    fun userManifestReplacesTheBuiltInWithTheSameId() {
        val dir = tempDir()
        File(dir, "mine-pack.json").writeText(minimal("glasspane", "9.9.9"))
        val registry = PackRegistry.load(dir)
        assertEquals("9.9.9", registry.byId("glasspane")!!.pack_version)
    }

    @Test
    fun noDirectoryFallsBackToTheVendoredReference() {
        val registry = PackRegistry.load(null)
        assertNotNull(registry.byId("glasspane"))
    }

    // ─── Per-app selection ───────────────────────────────────────────────

    @Test
    fun selectionPrefersExplicitThenDocumentReferencesThenSoleManifest() {
        val dir = tempDir()
        File(dir, "alpha-pack.json").writeText(minimal("alpha"))
        File(dir, "beta-pack.json").writeText(minimal("beta"))
        val registry = PackRegistry.load(dir)

        val plain = AppSpec(id = "app", views = listOf(ViewSpec(title = "V")))
        // Explicit id wins.
        assertEquals("beta", registry.selectedPack(plain, "beta")!!.pack_id)
        // A document already referencing a pack selects it.
        val referencing = plain.copy(views = listOf(ViewSpec(
            title = "V",
            source = SourceRef.Pack("alpha", "alpha.things"),
        )))
        assertEquals("alpha", registry.selectedPack(referencing)!!.pack_id)
        // A pack action also counts as a reference.
        val acting = plain.copy(views = listOf(ViewSpec(
            title = "V",
            actions = listOf(ActionDef.PackAction("beta", "b.act")),
        )))
        assertEquals("beta", registry.selectedPack(acting)!!.pack_id)
        // Several manifests, no reference, no explicit pick: none selected.
        assertNull(registry.selectedPack(plain))
        // A sole installed manifest is the default.
        val sole = PackRegistry.load(tempDir().also {
            File(it, "only-pack.json").writeText(minimal("glasspane"))
        })
        assertEquals("glasspane", sole.selectedPack(plain)!!.pack_id)
    }

    @Test
    fun selectionPrefersTheDeclaredPackOverAmbiguity() {
        val dir = tempDir()
        File(dir, "alpha-pack.json").writeText(minimal("alpha"))
        File(dir, "beta-pack.json").writeText(minimal("beta"))
        val registry = PackRegistry.load(dir)
        // The declared #+JETPACS_PACK: wins even before any view references
        // it, and even with several manifests installed (where singleOrNull
        // would give null) — pickers and the exporter agree on it.
        val declared = AppSpec(id = "app", pack = PackRef("beta"),
                               views = listOf(ViewSpec(title = "V")))
        assertEquals("beta", registry.selectedPack(declared)!!.pack_id)
    }
}
